import React from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'

const input = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100'
const emptyForm = { title: '', description: '', start_at: '', end_at: '', all_day: false, color: '#2563eb', notes: '', reminder_minutes: '', attendee_ids: '' }
const pad = value => String(value).padStart(2, '0')
const localValue = value => { if (!value) return ''; const date = new Date(value); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }
const dayKey = value => { const date = new Date(value); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` }
const timeText = value => new Date(value).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hour12: true })
const dateTimeText = value => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true })
const errorText = error => typeof error?.response?.data?.detail === 'string' ? error.response.data.detail : 'Unable to complete the calendar action.'

function rangeFor(anchor, view) {
  const start = new Date(anchor); start.setHours(0, 0, 0, 0)
  if (view === 'month') { start.setDate(1); start.setDate(start.getDate() - start.getDay()) }
  if (view === 'week') start.setDate(start.getDate() - start.getDay())
  const end = new Date(start); end.setDate(end.getDate() + (view === 'month' ? 42 : view === 'week' ? 7 : 1))
  return { start, end }
}

export default function CompanyCalendar() {
  const qc = useQueryClient()
  const [companyId, setCompanyId] = React.useState('')
  const [view, setView] = React.useState('month')
  const [anchor, setAnchor] = React.useState(() => new Date())
  const [editor, setEditor] = React.useState(null)
  const [selected, setSelected] = React.useState(null)
  const companies = useQuery({ queryKey: ['task-companies'], queryFn: () => api.get('/api/tasks/companies').then(r => r.data.companies) })
  React.useEffect(() => { if (!companyId && companies.data?.length) setCompanyId(String(companies.data[0].id)) }, [companies.data, companyId])
  const range = rangeFor(anchor, view)
  const events = useQuery({
    queryKey: ['company-calendar', companyId, range.start.toISOString(), range.end.toISOString()],
    enabled: Boolean(companyId),
    queryFn: () => api.get('/api/company-calendar', { params: { company_id: companyId, start: range.start.toISOString(), end: range.end.toISOString() } }).then(r => r.data.events),
  })
  const refresh = () => qc.invalidateQueries({ queryKey: ['company-calendar'] })
  const move = amount => setAnchor(current => { const next = new Date(current); view === 'month' ? next.setMonth(next.getMonth() + amount) : next.setDate(next.getDate() + amount * (view === 'week' ? 7 : 1)); return next })
  const openCreate = date => setEditor({ mode: 'create', event: { ...emptyForm, start_at: localValue(date || anchor), end_at: localValue(date || anchor) } })
  const openEvent = event => event.source_type === 'task' ? setEditor({ mode: 'task', event: { ...event, start_at: localValue(event.start_at) } }) : setSelected(event.id)
  return <main className="mx-auto max-w-7xl space-y-5 px-3 py-5 sm:px-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-700">Company Management</p><h1 className="text-2xl font-bold text-blue-950">Company Calendar</h1><p className="text-sm text-slate-500">Events, reminders, and task deadlines in one place.</p></div><button disabled={!companyId} onClick={() => openCreate()} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">New Event</button></header>
    <section className="rounded-xl bg-white p-3 shadow-sm sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="min-w-56 text-xs font-semibold text-slate-600">Company<select aria-label="Company" className={`${input} mt-1`} value={companyId} onChange={e => { setCompanyId(e.target.value); setSelected(null) }}><option value="">Select a company</option>{(companies.data || []).map(company => <option key={company.id} value={company.id}>{company.legal_name}</option>)}</select></label><div className="flex flex-wrap items-center gap-2"><button aria-label="Previous" onClick={() => move(-1)} className="rounded border px-3 py-2">‹</button><button onClick={() => setAnchor(new Date())} className="rounded border px-3 py-2 text-sm font-medium">Today</button><button aria-label="Next" onClick={() => move(1)} className="rounded border px-3 py-2">›</button><strong className="min-w-44 px-2 text-center text-blue-950">{anchor.toLocaleDateString([], { month: 'long', year: 'numeric', ...(view === 'day' ? { day: 'numeric' } : {}) })}</strong><div className="flex rounded-lg bg-slate-100 p-1">{['month', 'week', 'day'].map(option => <button key={option} onClick={() => setView(option)} className={`rounded-md px-3 py-1.5 text-sm capitalize ${view === option ? 'bg-white font-semibold text-blue-700 shadow' : 'text-slate-600'}`}>{option[0].toUpperCase() + option.slice(1)}</button>)}</div></div></div></section>
    {!companyId ? <Empty>Select a company to view its calendar.</Empty> : events.isLoading ? <Empty>Loading calendar…</Empty> : <CalendarGrid view={view} anchor={anchor} range={range} events={events.data || []} onEvent={openEvent} onDay={openCreate} />}
    {editor && <EventEditor companyId={companyId} state={editor} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); refresh() }} />}
    {selected !== null && <EventDetail eventId={selected} onClose={() => setSelected(null)} onEdit={event => { setSelected(null); setEditor({ mode: 'edit', event: { ...event, start_at: localValue(event.start_at), end_at: localValue(event.end_at) } }) }} />}
  </main>
}

function CalendarGrid({ view, anchor, range, events, onEvent, onDay }) {
  const count = view === 'month' ? 42 : view === 'week' ? 7 : 1
  const days = Array.from({ length: count }, (_, index) => { const value = new Date(range.start); value.setDate(value.getDate() + index); return value })
  return <section className="overflow-hidden rounded-xl bg-white shadow-sm"><div className={`grid ${count === 1 ? 'grid-cols-1' : 'grid-cols-7'} border-b bg-slate-50`}>{days.slice(0, count === 1 ? 1 : 7).map(day => <div key={day.toISOString()} className="p-2 text-center text-xs font-semibold uppercase text-slate-500">{day.toLocaleDateString([], { weekday: view === 'day' ? 'long' : 'short' })}</div>)}</div><div className={`grid ${count === 1 ? 'grid-cols-1' : 'grid-cols-7'}`}>{days.map(day => { const items = events.filter(event => dayKey(event.start_at) === dayKey(day)); const muted = view === 'month' && day.getMonth() !== anchor.getMonth(); return <div key={day.toISOString()} className={`min-h-32 border-b border-r p-1.5 sm:min-h-40 sm:p-2 ${muted ? 'bg-slate-50 text-slate-400' : ''}`}><button aria-label={`Create event on ${dayKey(day)}`} onClick={() => onDay(day)} className={`mb-1 flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${dayKey(day) === dayKey(new Date()) ? 'bg-blue-700 text-white' : 'hover:bg-blue-50'}`}>{day.getDate()}</button><div className="space-y-1">{items.map(event => <button key={event.id} onClick={() => onEvent(event)} title={event.title} className="block w-full truncate rounded px-2 py-1 text-left text-xs font-medium text-white" style={{ backgroundColor: event.color || '#2563eb' }}><span className="hidden sm:inline">{event.all_day ? 'All day' : timeText(event.start_at)} · </span>{event.source_type === 'task' ? 'Task deadline: ' : ''}{event.title}</button>)}</div></div> })}</div>{!events.length && <p className="border-t p-5 text-center text-sm text-slate-500">No events in this period.</p>}</section>
}

function EventEditor({ companyId, state, onClose, onSaved }) {
  const [form, setForm] = React.useState(state.event)
  const change = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const mutation = useMutation({ mutationFn: () => {
    if (state.mode === 'task') return api.put(`/api/company-calendar/${form.id}`, { start_at: new Date(form.start_at).toISOString() })
    const payload = { company_id: Number(companyId), title: form.title.trim(), description: form.description || null, start_at: new Date(form.start_at).toISOString(), end_at: form.end_at ? new Date(form.end_at).toISOString() : null, all_day: form.all_day, color: form.color, notes: form.notes || null, reminder_minutes: form.reminder_minutes === '' ? null : Number(form.reminder_minutes), attendee_ids: String(form.attendee_ids || '').split(',').map(item => item.trim()).filter(Boolean) }
    return state.mode === 'create' ? api.post('/api/company-calendar', payload) : api.put(`/api/company-calendar/${form.id}`, payload)
  }, onSuccess: onSaved })
  if (state.mode === 'task') return <Modal title="Edit Task Deadline" onClose={onClose}><form className="space-y-4" onSubmit={e => { e.preventDefault(); mutation.mutate() }}><p className="rounded-lg bg-amber-50 p-3 text-sm">Task deadline: <strong>{form.title}</strong>. Calendar edits update the source task.</p><Field label="Due date and time"><input aria-label="Start" required type="datetime-local" className={input} value={form.start_at} onChange={e => change('start_at', e.target.value)} /></Field><Save mutation={mutation} disabled={!form.start_at} label="Update task date" /></form></Modal>
  return <Modal title={state.mode === 'create' ? 'Create Event' : 'Edit Event'} onClose={onClose}><form className="space-y-4" onSubmit={e => { e.preventDefault(); mutation.mutate() }}><Field label="Event title"><input aria-label="Event title" required maxLength="300" className={input} value={form.title} onChange={e => change('title', e.target.value)} /></Field><Field label="Description"><textarea aria-label="Description" rows="3" className={input} value={form.description || ''} onChange={e => change('description', e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Start"><input aria-label="Start" required type="datetime-local" className={input} value={form.start_at} onChange={e => change('start_at', e.target.value)} /></Field><Field label="End"><input aria-label="End" type="datetime-local" className={input} value={form.end_at || ''} onChange={e => change('end_at', e.target.value)} /></Field></div><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input aria-label="All day" type="checkbox" checked={form.all_day} onChange={e => change('all_day', e.target.checked)} />All day</label><Field label="Color"><input aria-label="Color" type="color" className="h-10 w-full rounded border p-1" value={form.color} onChange={e => change('color', e.target.value)} /></Field></div><Field label="Notes"><textarea aria-label="Notes" rows="2" className={input} value={form.notes || ''} onChange={e => change('notes', e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Reminder (minutes before)"><input aria-label="Reminder" type="number" min="0" max="525600" className={input} value={form.reminder_minutes ?? ''} onChange={e => change('reminder_minutes', e.target.value)} /></Field><Field label="Attendees (employee IDs, comma separated)"><input aria-label="Attendees" className={input} value={Array.isArray(form.attendee_ids) ? form.attendee_ids.join(', ') : form.attendee_ids || ''} onChange={e => change('attendee_ids', e.target.value)} /></Field></div>{mutation.isError && <p role="alert" className="text-sm text-red-700">{errorText(mutation.error)}</p>}<Save mutation={mutation} disabled={!form.title.trim() || !form.start_at} label={state.mode === 'create' ? 'Create Event' : 'Save Event'} /></form></Modal>
}

function EventDetail({ eventId, onClose, onEdit }) {
  const query = useQuery({ queryKey: ['calendar-event', eventId], queryFn: () => api.get(`/api/company-calendar/events/${eventId}`).then(r => r.data) })
  const upload = useMutation({ mutationFn: file => { const data = new FormData(); data.append('file', file); return api.post(`/api/company-calendar/events/${eventId}/attachments`, data) }, onSuccess: () => query.refetch() })
  const event = query.data
  return <Modal title="Event Details" onClose={onClose}>{query.isLoading ? <p>Loading event…</p> : event && <div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-blue-950">{event.title}</h3><p className="text-sm text-slate-500">{event.all_day ? 'All day' : dateTimeText(event.start_at)}{event.end_at ? ` – ${dateTimeText(event.end_at)}` : ''}</p></div><button onClick={() => onEdit(event)} className="rounded border px-3 py-2 text-sm font-semibold">Edit</button></div><p className="whitespace-pre-wrap text-sm">{event.description || 'No description.'}</p>{event.notes && <div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>Notes</strong><p className="mt-1 whitespace-pre-wrap">{event.notes}</p></div>}<section><h3 className="font-semibold">Attachments</h3><label className="mt-2 inline-block cursor-pointer rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white">Upload attachment<input aria-label="Upload attachment" type="file" className="sr-only" onChange={e => e.target.files?.[0] && upload.mutate(e.target.files[0])} /></label>{upload.isError && <p className="mt-2 text-sm text-red-700">{errorText(upload.error)}</p>}<ul className="mt-2 space-y-1 text-sm">{(event.attachments || []).map(file => <li key={file.id} className="rounded bg-slate-50 px-3 py-2">{file.filename} <span className="text-slate-400">({file.content_type})</span></li>)}{!event.attachments?.length && <li className="text-slate-500">No attachments.</li>}</ul></section><section><h3 className="font-semibold">Audit history</h3><ol className="mt-2 space-y-2 border-l-2 border-blue-100 pl-4">{(event.audit || []).map((item, index) => <li key={`${item.created_at}-${index}`} className="text-sm"><p className="font-medium capitalize">{item.action.replaceAll('_', ' ')}</p><p className="text-xs text-slate-500">{item.actor_employee_id} · {item.created_at ? dateTimeText(item.created_at) : ''}</p>{item.detail && <p className="text-xs text-slate-600">{item.detail}</p>}</li>)}{!event.audit?.length && <li className="text-sm text-slate-500">No audit entries.</li>}</ol></section></div>}</Modal>
}

function Field({ label, children }) { return <label className="block text-xs font-semibold text-slate-600">{label}<span className="mt-1 block">{children}</span></label> }
function Save({ mutation, disabled, label }) { return <div>{mutation.isError && <p role="alert" className="mb-2 text-sm text-red-700">{errorText(mutation.error)}</p>}<button type="submit" disabled={disabled || mutation.isPending} className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending ? 'Saving…' : label}</button></div> }
function Empty({ children }) { return <section className="rounded-xl bg-white p-12 text-center text-slate-500 shadow-sm">{children}</section> }
function Modal({ title, onClose, children }) { return <div role="presentation" className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-3" onMouseDown={e => e.target === e.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-label={title} className="mx-auto my-6 max-w-2xl rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><header className="mb-5 flex items-center justify-between gap-4"><h2 className="text-xl font-bold text-blue-950">{title}</h2><button onClick={onClose} className="rounded px-2 py-1 text-sm text-slate-500 hover:bg-slate-100">Close</button></header>{children}</section></div> }
