import React from 'react'
import { api } from '../lib/api'
import WorkflowNav from '../components/WorkflowNav'

const field='w-full rounded-lg border border-gray-300 px-3 py-2'
const blank={company_id:'',category_id:'',name:'',username:'',password:'',url:'',account_ref:'',mfa_notes:'',recovery_notes:'',notes:''}
export const VAULT_ACTIVITY_EVENTS=['pointerdown','keydown','scroll','touchstart']
export function filterVaultEntries(entries,company,search){const q=(search||'').trim().toLowerCase();return entries.filter(e=>(!company||String(e.company_id)===String(company))&&(!q||`${e.name} ${e.username||''} ${e.url||''} ${e.notes||''} ${e.account_ref||''} ${e.mfa_notes||''} ${e.recovery_notes||''} ${e.category||''}`.toLowerCase().includes(q)))}
export function groupVaultEntries(entries,companies,company=''){const rows=filterVaultEntries(entries,company,''),out={};for(const c of companies){const matches=rows.filter(e=>String(e.company_id)===String(c.id));if(matches.length)out[c.legal_name]=matches}for(const e of rows){if(!companies.some(c=>String(c.id)===String(e.company_id)))(out[`Company ${e.company_id}`]||=[]).push(e)}return out}
function message(error,fallback){const detail=error?.response?.data?.detail;return typeof detail==='string'?detail:fallback}
function stamp(value){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',hour12:true}).format(new Date(value)):''}

export default function PasswordVault(){
 const [configured,setConfigured]=React.useState(null),[lockMinutes,setLockMinutes]=React.useState(15),[token,setToken]=React.useState(''),[password,setPassword]=React.useState(''),[entries,setEntries]=React.useState([]),[companies,setCompanies]=React.useState([]),[categories,setCategories]=React.useState([]),[company,setCompany]=React.useState(''),[search,setSearch]=React.useState(''),[error,setError]=React.useState(''),[form,setForm]=React.useState(blank),[editing,setEditing]=React.useState(null),[categoryOpen,setCategoryOpen]=React.useState(false),[audit,setAudit]=React.useState(null),[revealed,setRevealed]=React.useState({}),[copied,setCopied]=React.useState('')
 const tokenRef=React.useRef(''),timer=React.useRef();tokenRef.current=token
 const headers=t=>({'X-Vault-Token':t||tokenRef.current})
 React.useEffect(()=>{api.get('/api/password-vault/status').then(r=>{setConfigured(r.data.configured);setLockMinutes(r.data.lock_minutes||15)}).catch(e=>setError(message(e,'Password Vault is not available for this account.')));api.get('/api/tasks/companies').then(r=>{const rows=r.data.companies||[];setCompanies(rows);setForm(f=>({...f,company_id:rows[0]?.id||''}))}).catch(()=>{})},[])
 const clear=React.useCallback(()=>{clearTimeout(timer.current);tokenRef.current='';setToken('');setEntries([]);setRevealed({});setCopied('')},[])
 const lock=React.useCallback(async(send=true)=>{const current=tokenRef.current;clear();if(send&&current)try{await api.post('/api/password-vault/lock',null,{headers:headers(current)})}catch{}},[clear])
 React.useEffect(()=>{if(!token)return;const reset=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>lock(true),lockMinutes*60000)};VAULT_ACTIVITY_EVENTS.forEach(x=>window.addEventListener(x,reset,{passive:true}));reset();return()=>{clearTimeout(timer.current);VAULT_ACTIVITY_EVENTS.forEach(x=>window.removeEventListener(x,reset))}},[token,lockMinutes,lock])
 const guarded=async fn=>{setError('');try{return await fn()}catch(e){if(e?.response?.status===423)clear();setError(message(e,'Unable to complete vault action.'));throw e}}
 const load=async(t=tokenRef.current,rows=companies)=>{if(!rows.length)return;const results=await Promise.all(rows.map(c=>api.get('/api/password-vault/entries',{params:{company_id:c.id},headers:headers(t)}).then(r=>r.data.entries||[])));setEntries(results.flat());try{const r=await api.get('/api/password-vault/categories',{headers:headers(t)});setCategories(r.data.categories||[])}catch{setCategories([])}}
 React.useEffect(()=>{if(token&&companies.length)load()},[token,companies.length])
 const unlock=async e=>{e.preventDefault();await guarded(async()=>{if(!configured){await api.post('/api/password-vault/configure',{password});setConfigured(true);setPassword('');return}const r=await api.post('/api/password-vault/unlock',{password});tokenRef.current=r.data.vault_token;setToken(r.data.vault_token);setPassword('');setLockMinutes(r.data.expires_in_minutes||lockMinutes);await load(r.data.vault_token,companies)})}
 const save=async e=>{e.preventDefault();await guarded(async()=>{const payload={...form,company_id:Number(form.company_id),category_id:form.category_id?Number(form.category_id):null};if(editing){if(!payload.password)delete payload.password;await api.put(`/api/password-vault/entries/${editing}`,payload,{headers:headers()})}else await api.post('/api/password-vault/entries',payload,{headers:headers()});setEditing(null);setForm({...blank,company_id:companies[0]?.id||''});await load()})}
 const reveal=async id=>guarded(async()=>{const r=await api.post(`/api/password-vault/entries/${id}/reveal`,null,{headers:headers()});setRevealed(v=>({...v,[id]:r.data.password}));setCopied('')})
 const copy=async id=>guarded(async()=>{const r=await api.post(`/api/password-vault/entries/${id}/copy`,null,{headers:headers()});await navigator.clipboard.writeText(r.data.password);setCopied(id);setTimeout(()=>setCopied(''),2000)})
 const archive=async id=>{if(!confirm('Archive this credential?'))return;await guarded(async()=>{await api.delete(`/api/password-vault/entries/${id}`,{headers:headers()});await load()})}
 const showAudit=async()=>guarded(async()=>{const companyId=company||companies[0]?.id;if(!companyId)return;const r=await api.get('/api/password-vault/audit',{params:{company_id:companyId},headers:headers()});setAudit(r.data.events||[])})
 if(configured===null)return <div className="min-h-screen bg-slate-50 text-slate-900"><WorkflowNav/><main className="mx-auto max-w-md p-6"><h1 className="text-2xl font-bold">Password Vault</h1><p className="mt-4">Loading secure vault…</p>{error&&<p role="alert" className="text-red-700">{error}</p>}</main></div>
 if(!token)return <div className="min-h-screen bg-slate-50 text-slate-900"><WorkflowNav/><main className="mx-auto max-w-md p-6"><h1 className="text-2xl font-bold">Password Vault</h1><p className="my-3 text-sm text-gray-600">{configured?'Enter your separate vault password.':'Configure a separate vault password of at least 12 characters. This is not your login PIN.'}</p><form onSubmit={unlock}><label>Vault Password<input autoComplete="off" type="password" className={field} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-3 rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={password.length<12}>{configured?'Unlock Vault':'Configure Vault'}</button></form>{error&&<p role="alert" className="mt-2 text-red-700">{error}</p>}</main></div>
 const filtered=filterVaultEntries(entries,company,search),groups=groupVaultEntries(filtered,companies)
 return <div className="min-h-screen bg-slate-50 text-slate-900"><WorkflowNav/><main className="mx-auto max-w-6xl space-y-5 p-3 sm:p-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Password Vault</h1><p className="text-sm text-gray-500">Secrets stay masked and the vault locks after {lockMinutes||15} minutes of inactivity.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setCategoryOpen(true)} className="rounded-lg border bg-white px-4 py-2">Manage categories</button><button onClick={showAudit} className="rounded-lg border bg-white px-4 py-2">View audit</button><button onClick={()=>lock(true)} className="rounded-lg border border-red-300 bg-white px-4 py-2 font-semibold text-red-700">Lock Now</button></div></header>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
 <section className="rounded-xl bg-white p-4 shadow"><h2 className="mb-3 font-semibold">{editing?'Edit credential':'Add credential'}</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={save}><label>Company<select required className={field} value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}>{companies.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Category<select className={field} value={form.category_id||''} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Record Name<input required className={field} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Username<input autoComplete="off" className={field} value={form.username||''} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input required={!editing} autoComplete="new-password" type="password" className={field} placeholder={editing?'Leave blank to keep current password':''} value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>URL<input type="url" className={field} value={form.url||''} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>Account Number / Client ID<input autoComplete="off" className={field} value={form.account_ref||''} onChange={e=>setForm({...form,account_ref:e.target.value})}/></label><label>MFA / 2FA Notes<textarea className={field} value={form.mfa_notes||''} onChange={e=>setForm({...form,mfa_notes:e.target.value})}/></label><label className="md:col-span-2">Recovery Notes<textarea className={field} value={form.recovery_notes||''} onChange={e=>setForm({...form,recovery_notes:e.target.value})}/></label><label className="md:col-span-2">Notes<textarea className={field} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="flex gap-2"><button className="rounded-lg bg-blue-700 px-4 py-2 text-white">{editing?'Save changes':'Save Credential'}</button>{editing&&<button type="button" className="rounded border px-4" onClick={()=>{setEditing(null);setForm({...blank,company_id:companies[0]?.id||''})}}>Cancel</button>}</div></form></section>
 <section className="grid gap-3 rounded-xl bg-white p-4 shadow sm:grid-cols-2"><label>Filter by company<select className={field} value={company} onChange={e=>setCompany(e.target.value)}><option value="">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Search credentials<input className={field} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, category, username, URL, or notes"/></label></section>
 {Object.entries(groups).map(([name,rows])=><section key={name} className="rounded-xl bg-white p-4 shadow"><h2 className="border-b pb-2 text-lg font-semibold text-blue-950">{name}</h2><ul className="divide-y">{rows.map(e=><li key={e.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto]"><div><strong>{e.name}</strong>{e.category&&<span className="ml-2 rounded bg-slate-100 px-2 py-0.5 text-xs">{e.category}</span>}<p className="text-sm text-gray-600">Username: {e.username||'—'}</p><p aria-label={`${e.name} masked password`} className="font-mono text-sm">Password: {revealed[e.id]||e.password_masked||'••••••••'}</p>{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="text-sm text-blue-700">Open website ↗</a>}{e.account_ref&&<p className="mt-1 text-sm text-gray-600">Account / Client ID: {e.account_ref}</p>}{e.mfa_notes&&<p className="mt-1 text-sm text-gray-500">MFA: {e.mfa_notes}</p>}{e.recovery_notes&&<p className="mt-1 text-sm text-gray-500">Recovery: {e.recovery_notes}</p>}{e.notes&&<p className="mt-1 text-sm text-gray-500">{e.notes}</p>}</div><div className="flex flex-wrap items-center gap-2"><button className="rounded border px-3 py-2 text-sm text-blue-700" onClick={()=>reveal(e.id)}>Reveal</button><button className="rounded border px-3 py-2 text-sm" onClick={()=>copy(e.id)}>{copied===e.id?'Copied':'Copy password'}</button><button className="rounded border px-3 py-2 text-sm" onClick={()=>{setEditing(e.id);setForm({...e,password:''});scrollTo({top:0,behavior:'smooth'})}}>Edit credential</button><button className="rounded border border-red-200 px-3 py-2 text-sm text-red-700" onClick={()=>archive(e.id)}>Archive credential</button></div></li>)}</ul></section>)}{!filtered.length&&<p className="rounded-xl bg-white p-8 text-center text-gray-500 shadow">No credentials match this filter.</p>}
 {categoryOpen&&<CategoryManager categories={categories} headers={headers} close={()=>setCategoryOpen(false)} changed={()=>load()}/>} {audit&&<Modal title="Credential audit" close={()=>setAudit(null)}><ol className="space-y-2">{audit.map((a,i)=><li key={a.id||i} className="rounded bg-slate-50 p-3 text-sm"><strong>{a.action}</strong><p>{a.actor_name||a.actor_employee_id||a.employee_id||'Unknown user'} · {stamp(a.created_at)}</p>{a.detail&&<p>{a.detail}</p>}</li>)}</ol>{!audit.length&&<p>No audit activity.</p>}</Modal>}
 </main></div>
}
function CategoryManager({categories,headers,close,changed}){const [name,setName]=React.useState(''),[error,setError]=React.useState('');const add=async e=>{e.preventDefault();try{await api.post('/api/password-vault/categories',{name},{headers:headers()});setName('');changed()}catch(x){setError(message(x,'Unable to add category.'))}};const archive=async id=>{await api.delete(`/api/password-vault/categories/${id}`,{headers:headers()});changed()};return <Modal title="Manage categories" close={close}><form className="flex gap-2" onSubmit={add}><input required className={field} value={name} onChange={e=>setName(e.target.value)} placeholder="Category name"/><button className="rounded bg-blue-700 px-4 text-white">Add</button></form>{error&&<p role="alert" className="text-red-700">{error}</p>}<ul className="mt-4 divide-y">{categories.map(c=><li className="flex justify-between py-2" key={c.id}>{c.name}<button className="text-sm text-red-700" onClick={()=>archive(c.id)}>Archive</button></li>)}</ul></Modal>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-3"><section role="dialog" aria-modal="true" aria-label={title} className="mx-auto my-8 max-w-xl rounded-xl bg-white p-5"><header className="mb-4 flex justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={close}>Close</button></header>{children}</section></div>}
