import React from 'react'
import { api } from '../lib/api'

const field='w-full rounded-lg border border-gray-300 px-3 py-2'
export const VAULT_ACTIVITY_EVENTS=['pointerdown','keydown','scroll','touchstart']
export function filterVaultEntries(entries,company,search){const q=(search||'').trim().toLowerCase();return entries.filter(e=>(!company||String(e.company_id)===String(company))&&(!q||`${e.name} ${e.username||''} ${e.url||''} ${e.notes||''}`.toLowerCase().includes(q)))}
export function groupVaultEntries(entries,companies,company=''){const rows=filterVaultEntries(entries,company,''),out={};for(const c of companies){const matches=rows.filter(e=>String(e.company_id)===String(c.id));if(matches.length)out[c.legal_name]=matches}for(const e of rows){if(!companies.some(c=>String(c.id)===String(e.company_id))){const name=`Company ${e.company_id}`;(out[name]||=[]).push(e)}}return out}
function message(error,fallback){const detail=error?.response?.data?.detail;return typeof detail==='string'?detail:fallback}

export default function PasswordVault(){
 const [configured,setConfigured]=React.useState(null),[lockMinutes,setLockMinutes]=React.useState(15),[token,setToken]=React.useState(''),[password,setPassword]=React.useState(''),[entries,setEntries]=React.useState([]),[companies,setCompanies]=React.useState([]),[company,setCompany]=React.useState(''),[search,setSearch]=React.useState(''),[error,setError]=React.useState(''),[form,setForm]=React.useState({company_id:'',name:'',username:'',password:'',url:'',notes:''}),[revealed,setRevealed]=React.useState({}),[copied,setCopied]=React.useState('')
 const tokenRef=React.useRef(''),timer=React.useRef();tokenRef.current=token
 React.useEffect(()=>{api.get('/api/password-vault/status').then(r=>{setConfigured(r.data.configured);setLockMinutes(r.data.lock_minutes||15)}).catch(e=>setError(message(e,'Password Vault is not available for this account.')));api.get('/api/tasks/companies').then(r=>{const rows=r.data.companies||[];setCompanies(rows);setForm(f=>({...f,company_id:f.company_id||rows[0]?.id||''}))}).catch(()=>{})},[])
 const headers=t=>({'X-Vault-Token':t||tokenRef.current})
 const clear=React.useCallback(()=>{clearTimeout(timer.current);tokenRef.current='';setToken('');setEntries([]);setRevealed({});setCopied('')},[])
 const lock=React.useCallback(async(send=true)=>{const current=tokenRef.current;clear();if(send&&current)try{await api.post('/api/password-vault/lock',null,{headers:headers(current)})}catch{}},[clear])
 React.useEffect(()=>{if(!token)return;const reset=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>lock(true),lockMinutes*60*1000)};VAULT_ACTIVITY_EVENTS.forEach(x=>window.addEventListener(x,reset,{passive:true}));reset();return()=>{clearTimeout(timer.current);VAULT_ACTIVITY_EVENTS.forEach(x=>window.removeEventListener(x,reset))}},[token,lockMinutes,lock])
 const guarded=async(fn)=>{setError('');try{return await fn()}catch(e){if(e?.response?.status===423)clear();setError(message(e,'Unable to complete vault action.'));throw e}}
 const load=async t=>{const r=await api.get('/api/password-vault/entries',{headers:headers(t)});setEntries(r.data.entries||[])}
 const unlock=async e=>{e.preventDefault();await guarded(async()=>{if(!configured){await api.post('/api/password-vault/configure',{password});setConfigured(true);setPassword('');return}const r=await api.post('/api/password-vault/unlock',{password});tokenRef.current=r.data.vault_token;setToken(r.data.vault_token);setPassword('');setLockMinutes(r.data.expires_in_minutes||lockMinutes);await load(r.data.vault_token)})}
 const create=async e=>{e.preventDefault();await guarded(async()=>{await api.post('/api/password-vault/entries',{...form,company_id:Number(form.company_id)},{headers:headers()});setForm(f=>({...f,name:'',username:'',password:'',url:'',notes:''}));await load()})}
 const reveal=async id=>guarded(async()=>{const r=await api.post(`/api/password-vault/entries/${id}/reveal`,null,{headers:headers()});setRevealed(v=>({...v,[id]:r.data.password}));setCopied('')})
 const copy=async id=>{const secret=revealed[id];if(!secret)return;await navigator.clipboard.writeText(secret);setCopied(id);setTimeout(()=>setCopied(''),2000)}
 if(configured===null)return <main className="mx-auto max-w-md p-6"><h1 className="text-2xl font-bold">Password Vault</h1><p className="mt-4">Loading secure vault…</p>{error&&<p role="alert" className="text-red-700">{error}</p>}</main>
 if(!token)return <main className="mx-auto max-w-md p-6"><h1 className="text-2xl font-bold">Password Vault</h1><p className="my-3 text-sm text-gray-600">{configured?'Enter your separate vault password.':'Configure a separate vault password of at least 12 characters. This is not your login PIN.'}</p><form onSubmit={unlock}><label>Vault Password<input autoComplete="off" type="password" className={field} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-3 rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={password.length<12}>{configured?'Unlock Vault':'Configure Vault'}</button></form>{!configured&&<p className="mt-3 text-xs text-gray-500">After configuration, unlock the vault with the password you created.</p>}{error&&<p role="alert" className="mt-2 text-red-700">{error}</p>}</main>
 const filtered=filterVaultEntries(entries,company,search),groups=groupVaultEntries(filtered,companies)
 return <main className="mx-auto max-w-6xl space-y-5 p-6"><header className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Password Vault</h1><p className="text-sm text-gray-500">Secrets stay masked and the vault locks after {lockMinutes||15} minutes of inactivity.</p></div><button onClick={()=>lock(true)} className="rounded-lg border border-red-300 px-4 py-2 font-semibold text-red-700">Lock Now</button></header>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}
 <section className="rounded-xl bg-white p-4 shadow"><h2 className="mb-3 font-semibold">Add credential</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={create}><label>Company<select required className={field} value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}>{companies.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Record Name<input required className={field} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Username<input autoComplete="off" className={field} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input required autoComplete="new-password" type="password" className={field} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>URL<input type="url" className={field} value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>Notes<input className={field} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="rounded-lg bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={!form.company_id||!form.name||!form.password}>Save Credential</button></form></section>
 <section className="grid gap-3 rounded-xl bg-white p-4 shadow sm:grid-cols-2"><label>Filter by company<select className={field} value={company} onChange={e=>setCompany(e.target.value)}><option value="">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Search credentials<input className={field} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, username, URL, or notes"/></label></section>
 {Object.entries(groups).map(([name,rows])=><section key={name} className="rounded-xl bg-white p-4 shadow"><h2 className="border-b pb-2 text-lg font-semibold text-blue-950">{name}</h2><ul className="divide-y">{rows.map(e=><li key={e.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto]"><div><strong>{e.name}</strong><p className="text-sm text-gray-600">Username: {e.username||'—'}</p><p aria-label={`${e.name} masked password`} className="font-mono text-sm">Password: {revealed[e.id]||e.password_masked||'••••••••'}</p>{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="text-sm text-blue-700">Open website ↗</a>}{e.notes&&<p className="mt-1 text-sm text-gray-500">{e.notes}</p>}</div><div className="flex items-center gap-2"><button className="rounded border px-3 py-2 text-sm text-blue-700" onClick={()=>reveal(e.id)}>Reveal</button><button disabled={!revealed[e.id]} className="rounded border px-3 py-2 text-sm disabled:opacity-40" onClick={()=>copy(e.id)}>{copied===e.id?'Copied':'Copy password'}</button>{revealed[e.id]&&<button className="text-sm text-gray-600" onClick={()=>setRevealed(v=>({...v,[e.id]:undefined}))}>Hide</button>}</div></li>)}</ul></section>)}{!filtered.length&&<p className="rounded-xl bg-white p-8 text-center text-gray-500 shadow">No credentials match this filter.</p>}</main>
}
